data:
    dataset_directory: ""
    annotation_file: ""
    room_layout_size: "64,64"

network:


boundary_encoder:
    name: "resnet18"
    feature_size: 256
    freeze_bn: false
    input_channels: 1



