data:
    dataset_directory: ""
    annotation_file: ""
    room_layout_size: "64,64"
    attributes_num: 8
    object_max_num: 125
    class_num: 114

network:
    n_layers: 4
    n_heads: 8
    dimensions: 256
    feed_forward_dimensions: 1024
    max_sequence_length: 200
    sampler:
        hidden_input_dimension: 512
        hidden_output_dimension: 256
        output_dimension: 1

boundary_encoder:
    name: "resnet18"
    freeze_bn: False
    input_channels: 1
    feature_size: 256

training:
    dropout: 0.1
    batch_size: 32
    epoches: 100
    lr: 0.0001