data:
    dataset_directory: "D:\\Study\\Projects\\DeepLearning\\UrbanGeneration\\Indoor\\ATISS Remake\\data\\raw"
    annotation_file: ""
    room_layout_size: 256
    attributes_num: 8
    object_max_num: 5
    class_num: 10
    permutation_num: 100

network:
    n_layers: 8
    n_heads: 4
    dimensions: 256
    feed_forward_dimensions: 1024
    max_sequence_length: 40
    sampler:
        hidden_input_dimension: 512
        hidden_output_dimension: 256
        output_dimension: 1

boundary_encoder:
    name: "resnet18"
    freeze_bn: False
    input_channels: 1
    feature_size: 256

training:
    dropout: 0.3
    batch_size: 1
    epoches: 100
    checkpoint_frequency: 1
    lr: 0.00001