class_order:
  0: 'armchair'
  1: 'bookshelf'
  2: 'cabinet'
  3: 'ceiling_lamp'
  4: 'chair'
  5: 'children_cabinet'
  6: 'coffee_table'
  7: 'desk'
  8: 'double_bed'
  9: 'dressing_chair'
  10: 'dressing_table'
  11: 'kids_bed'
  12: 'nightstand'
  13: 'pendant_lamp'
  14: 'shelf'
  15: 'single_bed'
  16: 'sofa'
  17: 'stool'
  18: 'table'
  19: 'tv_stand'
  20: 'wardrobe'




