class_order:
  0: 'nightstand'
  1: 'double_bed'
  2: 'wardrobe'
  3: 'pendant_lamp'
  4: 'ceiling_lamp'
  5: 'tv_stand'
  6: 'chair'
  7: 'single_bed'
  8: 'dressing_table'
  9: 'cabinet'
  10: 'table'
  11: 'desk'
  12: 'stool'
  13: 'shelf'
  14: 'kids_bed'
  15: 'bookshelf'
  16: 'children_cabinet'
  17: 'dressing_chair'
  18: 'armchair'
  19: 'sofa'
  20: 'coffee_table'




